apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fraud-project
  namespace: argocd
spec:
  description: Projet ArgoCD pour le service de scoring de fraude
  sourceRepos:
    - https://github.com/DataScientest/ArgoCD_Course.git
  destinations:
    - namespace: fraud-detection
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
