apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: support-priority-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: #TODO:  <URL_DE_VOTRE_FORK>
    targetRevision: HEAD
    path: #TODO: compléter le chemin vers les manifests de l'environnement de dev
  destination:
    server: https://kubernetes.default.svc
    namespace: support-priority
  syncPolicy:
    automated: {}