apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraud-app-prod
  namespace: argocd
spec:
  project: fraud-project
  source:
    repoURL: https://github.com/DataScientest/ArgoCD_Course.git
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: fraud-detection
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
