apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: support-priority-api
  namespace: support-priority
spec:
  ingressClassName: nginx
  rules:
    - host: support-priority.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: support-priority-api
                port:
                  number: 80
